version: '3'

services:
 
  gateway:
    image: orogers/td-gateway:v0.0.1
    ports:
      - "80:80"



  td-frontend:
    image: orogers/td-frontend:v0.0.4
    ports:
      - "3000:3000"


  td-api:
    image: orogers/td-api:v0.0.3
    command: bash -c "python manage.py makemigrations && python manage.py makemigrations gear &&python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - MONGODBURL=mongodb+srv://ttuser:ttpassword@cluster0-wnuyh.mongodb.net/test?retryWrites=true&w=majority
