version: '3.7'

services:
  td-frontend:
    image: orogers/td-frontend:v0.0.1
    ports:
      - "80:80"
    depends_on: 
      - td-api


  td-api:
    image: orogers/td-api:v0.0.1
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - MONGODBURL=mongodb://mongodb:27017


  mongodb:
    image: mongo
    volumes:
      - /opt/mongo-volume:/data/db
    ports:
      - "27017:27017" 




